# example netlify.toml
[build]
command = "node -v"
# functions = "netlify/functions"
publish = "."


# [[plugins]]
# package = "/plugins/netlify-plugin-hello-world"


[[edge_functions]]
function = "react"
path = "/react"

[[edge_functions]]
function = "og"
path = "/og"


[[edge_functions]]
function = "rewrite"
path = "/rewrite"
## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
[[redirects]]
from = "/wildcard/*"
to = "/.netlify/images/:splat"
status = 200

[[redirects]]
from = "/wildcard301/*"
to = "/.netlify/images/:splat"

[[redirects]]
from = "/query"
query = { url = ":url", w = ":width", q = ":quality" }
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

[[redirects]]
from = "/_next/image"
query = { url = ":url", w = ":width", q = ":quality" }
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

[[redirects]]
from = "/query301"
query = { url = ":url", w = ":width", q = ":quality" }
to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
from = "/queryother"
query = { url = ":url", w = ":width", q = ":quality" }
to = "/path/image?url=:url&w=:width&q=:quality"
status = 200

[[redirects]]
from = "/wildcardother/*"
to = "/path/image"
status = 200

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file
## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
